version: "3.9"
services:
  samb-be:
    container_name: samb-be
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    init: true
    ports:
      - "2224:2224"
    environment:
      - VERSION= 1.0.0
      - REST_PORT=2224
      - GO_ENV=production
      - SWAGGER_HOST=localhost:2224
      - DB_HOST=disewa.id
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=Password*1!
      - DB_NAME=samb
      - DB_SSLMODE=disable
      - TIMEZONE=Asia/Jakarta
    networks:
      - net-vdi-meter
networks:
  net-vdi-meter:
    driver: bridge

